# Generated by Django 3.2.7 on 2021-09-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='usuario_edv',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='chave',
            name='usuario_nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
