# Generated by Django 3.2.7 on 2021-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210927_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='usuario_edv',
            field=models.CharField(default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='chave',
            name='usuario_nome',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
