# Generated by Django 3.2.7 on 2021-09-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210927_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
