# Generated by Django 3.2.7 on 2021-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_chave_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
